[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C = SG
ST = Sg
L = Sg
O = Training
CN = docker-registry.image-registry.svc.cluster.local

[v3_req]
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = docker-registry.image-registry.svc.cluster.local
DNS.2 = docker-registry.
DNS.3 = docker-registry..svc
DNS.4 = myregistry
