# 03-quota-redis.yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-redis
  namespace: gb-redis
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "10"
    persistentvolumeclaims: "10"
