grafana:
  enabled: true
  adminPassword: admin123

  nodeSelector:
    tier: backend

  persistence:
    enabled: true
    size: 5Gi

  service:
    type: ClusterIP

  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.observability.svc.cluster.local
      isDefault: false
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo.observability.svc.cluster.local:3100
      isDefault: false
      jsonData:
        httpMethod: GET
        serviceMap:
          datasourceUid: prometheus
        tracesToLogs:
          datasourceUid: Loki
        tracesToMetrics:
          datasourceUid: prometheus

alertmanager:
  enabled: true
  alertmanagerSpec:
    nodeSelector:
      tier: backend
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

prometheus:
  enabled: true
  prometheusSpec:
    nodeSelector:
      tier: backend
    retention: 3d
    retentionSize: 8GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
    resources:
      requests:
        cpu: 300m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

prometheusOperator:
  nodeSelector:
    tier: backend

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

kubeEtcd:
  enabled: false

kubeScheduler:
  enabled: false

kubeControllerManager:
  enabled: false

kubeProxy:
  enabled: false

defaultRules:
  create: true
